### ISSUE TITLE
Does it work with latest org-mode?

### ISSUE THREAD

**Issue by dsteuer** [w-vi/ox-wk.el#1]
Acitivated ox-wk by setting load-path and adding (require 'ox-wk) but get a warning:

unknown key word :export-block in init.el afterwards.

Is this something old from org-8.0 ?

thx
Detlef

**Comment by w-vi** [comment]
@dsteuer thanks for the report, I haven't tested it with latest 8.3.2 as I haven't updated it for a while. I guess that it has changed. I will look into it.

**Comment by dsteuer** [comment]
Maybe this is relevant:
http://permalink.gmane.org/gmane.emacs.orgmode/103736
Detlef

**Comment by w-vi** [comment]
I have tested with the lastest org-mode 8.3.3. and it works, can you please verify?

`Org-mode version 8.3.3 (8.3.3-17-gce80a0-elpa @ /home/wvi/.emacs.d/elpa/org-20160118/)`

**Comment by w-vi** [comment]
So it looks it has repaired itself for now as org-mode ignores it but according to news
http://orgmode.org/cgit.cgi/org-mode.git/tree/etc/ORG-NEWS?id=74c46ad0067ebf337f74ece4a86973c83adc7afa#n78
It should be removed and not used anymore. So I have removed it as well.

**Comment by w-vi** [comment]
@dsteuer If it doesn't help, try to grab the latest master where I have removed it.

**Comment by dsteuer** [comment]
Thx a lot! Works now here!
Detlef
