### ISSUE TITLE
ox-wk-export-to-wiki generates error

### ISSUE THREAD

**Issue by excalamus** [w-vi/ox-wk.el#10]
# Problem

Running `ox-wk-export-to-wiki` generates the error:

```
progn: Wrong type argument: symbolp, "utf-8"
```

# Version(s)
I am running `GNU Emacs 26.2 (build 1, x86_64-w64-mingw32) of 2019-04-13` on Windows 10.  The org-mode version is `Org mode version 9.2.3 (9.2.3-elpa @ c:/Users/<user>/.emacs.d/elpa/org-9.2.3/)`.

# Steps to generate error

1. Start `emacs -Q`
2. `C-x C-f ~/test.org`
3. Insert
```
* Header
Lorem ipsum dolor sit amet...
```
4. `C-x C-s`
5. `M-: (package-initialize)`
6. `ox-wk-export-to-wiki` 
7. Answer 'yes' to "Buffer test.txt modified; kill anyway? (yes or no)"

This produces the following output in `*Messages*`:
```
basic-save-buffer-2: Wrong type argument: symbolp, "utf-8"
```

# Workaround
Change `(org-export-coding-system "utf-8")` to `(org-export-coding-system nil)` in [the `ox-wk-export-to-wiki` function in `ox-wk.el`](https://github.com/w-vi/ox-wk.el/blob/3da2213be1874d9d3e8a9337b09003d9c102b943/ox-wk.el#L548).

At the moment, I'm not sure why the error happens or why this fixes it.

**Comment by w-vi** [comment]
Sorry for slow response but I was away and offline. Thanks a lot for the report I'll have a look.

**Comment by excalamus** [comment]
You're fine!  You released an entire library for free under the GPLv3!  I appreciate your work and am curious about what you find.

**Comment by flowsta** [comment]
still failing

**Comment by w-vi** [comment]
@flowsta Please can you provide details on what emacs and org-mode version is it happening on?
`M-x org-version`
`M-x emacs-version`

**Comment by f279801** [comment]
I'm facing the same issue.

> Org mode version 9.2.6
> GNU Emacs 26.3
