### ISSUE TITLE
stingp null if a list is empty

### ISSUE THREAD

**Issue by jschaeff** [w-vi/ox-wk.el#3]
Hi,

thanks for this exporter, it's very useful to me !

There is a bug if a list contains an empty item :

For instance : 

```
*test
- item 1
- 
```

shows :

`wrong type of argument: arrayp, nil`

**Comment by w-vi** [comment]
Hi, thanks a lot for the report I'll have a look.

**Comment by w-vi** [comment]
the issue was that empty content was being trimmed. It is fixed and I have introduced a CI sanity test. Hope it solves it for you.
