### ISSUE TITLE
Melpa release?

### ISSUE THREAD

**Issue by apiraino** [w-vi/ox-wk.el#5]
Hello,

I'm using this little nifty module and it looks stable enough. How about a release on Melpa? So one can install it as part of the initial setup of an EMACS environment, without needing a local copy or download link at hand.

Thanks!

**Comment by w-vi** [comment]
Good idea I haven't really thought about it for some reason. Will do.

**Comment by w-vi** [comment]
Melpa recipe submited: https://github.com/melpa/melpa/pull/5797

**Comment by w-vi** [comment]
It's out there: https://melpa.org/#/ox-wk

**Comment by apiraino** [comment]
Hurray, thank you so much!

(when you have a chance, pls also have a look at #7 with some README updates)
